line-length = 120
indent-width = 4
target-version = "py312"

[lint]
select =["ALL"]
ignore = ["D", "COM812", "INP001", "T201", "T203", "RET504", "RUF003"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"

[isort]
split-on-trailing-comma = false